### ISSUE TITLE
Monday, December 14, 2020

### ISSUE THREAD

**Issue by romebell** [SEI-ATL/UNIT_3#3]
### Please put issues here.

**Comment by maddevred** [comment]
not sure if mine is working/installed correctly or not 
![Screenshot from 2020-12-14 10-44-37](https://user-images.githubusercontent.com/73178321/102102161-7db38480-3df9-11eb-942d-1082aeae2827.png)

**Comment by canourrea23** [comment]
My clt is up to date but when I run  brew install mongodb-community@4.4  I get the screen shot error
```
➜  ~ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```
![Screen Shot 2020-12-14 at 10 46 28 AM](https://user-images.githubusercontent.com/73137943/102102306-a2a7f780-3df9-11eb-8728-ed5c13424580.png)

**Comment by NikkiHmltn** [comment]
<img width="487" alt="Screen Shot 2020-12-14 at 7 45 58 AM" src="https://user-images.githubusercontent.com/65046641/102102219-687e2c00-3de0-11eb-9a2f-91aa1f6dd222.png">
<img width="498" alt="Screen Shot 2020-12-14 at 7 46 19 AM" src="https://user-images.githubusercontent.com/65046641/102102274-75028480-3de0-11eb-9ff3-71bee10ba2d7.png">
<img width="490" alt="Screen Shot 2020-12-14 at 7 46 36 AM" src="https://user-images.githubusercontent.com/65046641/102102316-7f248300-3de0-11eb-8c25-3314dfe5b349.png">
<img width="492" alt="Screen Shot 2020-12-14 at 7 46 50 AM" src="https://user-images.githubusercontent.com/65046641/102102335-877cbe00-3de0-11eb-9f57-9c454e5eed5b.png">
<img width="484" alt="Screen Shot 2020-12-14 at 7 47 00 AM" src="https://user-images.githubusercontent.com/65046641/102102348-8d729f00-3de0-11eb-951f-9a6b50e38014.png">
 I tried to install using the prompts....think I done messed up

**Comment by maddevred** [comment]
@pmacaluso3 is this my carrot 
![Screenshot from 2020-12-14 10-50-16](https://user-images.githubusercontent.com/73178321/102102825-3bd70e00-3dfa-11eb-9c52-483b6c5484b3.png)

**Comment by NikkiHmltn** [comment]
<img width="494" alt="Screen Shot 2020-12-14 at 7 57 30 AM" src="https://user-images.githubusercontent.com/65046641/102103580-06262b00-3de2-11eb-84a0-3fdf9c7c6a0c.png">

**Comment by canourrea23** [comment]
> My clt is up to date but when I run brew install mongodb-community@4.4 I get the screen shot error
> 
> ```
> ➜  ~ xcode-select --install
> xcode-select: error: command line tools are already installed, use "Software Update" to install updates
> ```
> 
> ![Screen Shot 2020-12-14 at 10 46 28 AM](https://user-images.githubusercontent.com/73137943/102102306-a2a7f780-3df9-11eb-8728-ed5c13424580.png)

problem solved with https://developer.apple.com/download/more/

**Comment by lev-choubine** [comment]
![Screen Shot 2020-12-14 at 11 18 30 AM](https://user-images.githubusercontent.com/68445801/102106393-835f9900-3dfe-11eb-8e03-5385c2e1813d.png)
